regex:
  user_working_log:
    activity_types:
      on_task:
        requirement: !ruby/regexp /1. Requirement -/
        design: !ruby/regexp /2. Design -/
        coding: !ruby/regexp /3. Coding -/
        testing: !ruby/regexp /4. Testing -/
        bug_fixing: !ruby/regexp /5. Bug fixing -/
        release: !ruby/regexp /6. Release -/
        document: !ruby/regexp /Documents/
        support_customer: !ruby/regexp /^\[\Support/
      out_task:
        leave_off: !ruby/regexp /Leave off -/
        idle: !ruby/regexp /Idle -/
        meeting: !ruby/regexp /Communication - Meeting/
  sub_task:
    activity_types:
      clear_requirement: !ruby/regexp /1. Requirement -/
      detail_design: !ruby/regexp /2. Design -/
      code: !ruby/regexp /3. Coding -/
      test: !ruby/regexp /4. Testing -/
      bug: !ruby/regexp /5. Bug fixing -/
      release: !ruby/regexp /6. Release -/
static_subjects:
  has_not_parent:
    - '[ Documents ] -'
    - '[ Support ] -'
  has_parent:
    - '[ Investment Plan ] -'
redis:
  host: redis
  db: 15
  port: 6379
  key:
    fetch_story: Fetch_story
  expried:
    story: 300