daily_fetch_working_logs:
  cron: '0 9,18 * * 1-6'
  class: DailyFetchWorkingLogsWorker
  queue: default

update_reports_worker:
  cron: '0 19 * * 1-6'
  class: UpdateReportsWorker
  queue: default

fetch_all_report_worker:
  cron: '0 20 * * 1-6'
  class: FetchAllReportWorker
  queue: default

update_story_worker:
  cron: '0,30 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateStoryWorker
  queue: default
