daily_fetch_working_logs:
  cron: '30 8,18 * * 1-6'
  class: DailyFetchWorkingLogsWorker
  queue: default

update_reports_worker:
  cron: '0 19 * * 1-6'
  class: UpdateReportsWorker
  queue: default

fetch_all_report_worker:
  cron: '0 20 * * 1-6'
  class: FetchAllReportWorker
  queue: default

update_story_worker:
  cron: '30 7,20 * * 1-5'
  class: UpdateStoryWorker
  queue: default

update_actived_story_worker:
  cron: '0,15,30,45 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateActivedStoryWorker
  queue: default

update_init_story_redmine_worker:
  cron: '0,15,30,45 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateStoryRedmineWorker
  queue: default
  args: ['init']

update_in_progress_story_redmine_worker:
  cron: '0,15,30,45 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateStoryRedmineWorker
  queue: default
  args: ['in_progress']

update_resolved_story_redmine_worker:
  cron: '0,15,30,45 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateStoryRedmineWorker
  queue: default
  args: ['resolved']

update_feedback_story_redmine_worker:
  cron: '0,15,30,45 8,9,10,11,12,13,14,15,16,17,18 * * 1-5'
  class: UpdateStoryRedmineWorker
  queue: default
  args: ['feedback']
